services:
  - type: web
    name: ev-charging-booking-and-services
    env: python
    plan: free
    rootDir: ev_project_django
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && python manage.py seed_demo_data && python manage.py create_admin_user && gunicorn ev_service.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: SQLITE_PATH
        value: /tmp/db.sqlite3
      - key: DATABASE_URL
        fromDatabase:
          name: ev-charging-booking-and-services-db
          property: connectionString
databases:
  - name: ev-charging-booking-and-services-db
    plan: free
