# Generated by Django 5.0.2 on 2026-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('service_center', 'Service Center')], default='user', max_length=30),
        ),
    ]
