# Generated by Django 5.0.2 on 2026-02-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
        ('service_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='service_center.servicecenter'),
        ),
    ]
