# Generated by Django 5.0.2 on 2026-01-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='image',
            field=models.CharField(blank=True, help_text='Static image path or URL (optional)', max_length=300),
        ),
    ]
