# Generated by Django 5.0.2 on 2026-01-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0002_sparepart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='image',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL (optional)'),
        ),
    ]
