# Generated by Codex on 2026-02-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareparts", "0006_partorder_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partorder",
            name="points_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="partorder",
            name="points_redeemed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
