# Generated by Codex on 2026-02-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging", "0002_add_charging_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingbooking",
            name="payment_method",
            field=models.CharField(blank=True, choices=[("razorpay", "Razorpay")], default="", max_length=20),
        ),
        migrations.AddField(
            model_name="chargingbooking",
            name="razorpay_order_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="chargingbooking",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
