# Generated by Django 5.0.2 on 2026-02-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_chargingbooking_payment_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargingbooking',
            options={'ordering': ['-scheduled_at', '-created_at']},
        ),
    ]
