# Generated by Codex on 2026-02-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging", "0003_chargingbooking_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingbooking",
            name="points_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="chargingbooking",
            name="points_redeemed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
