# Generated by Codex on 2026-02-12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charging", "0004_alter_chargingbooking_options"),
        ("charging", "0004_chargingbooking_reward_points"),
    ]

    operations = []
