# Generated by Django 4.2 on 2025-11-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='contact',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
