# Generated by Django 4.2 on 2025-11-08 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0001_initial'),
        ('sos', '0002_sosalert_contact_sosalert_vehicle_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_centers', to='sos.sosalert')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_center.servicecenter')),
            ],
            options={
                'ordering': ['distance_km'],
            },
        ),
    ]
