# Generated by Django 4.2 on 2025-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('make', models.CharField(help_text='Manufacturer, e.g., Tesla', max_length=100)),
                ('model', models.CharField(help_text='Model name, e.g., Model 3', max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
