# Generated by Django 5.0.2 on 2026-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_servicebooking_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('gpay', 'GPay'), ('cash', 'Cash'), ('razorpay', 'Razorpay')], default='', max_length=20),
        ),
    ]
